# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relio < Formula
  desc "turn commits into releases"
  homepage "https://github.com/soyagvs/relio"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soyagvs/relio/releases/download/v1.3.0/relio_1.3.0_darwin_amd64.tar.gz"
      sha256 "4d24463a9e31e62f22977141c7017178dbd85fbaac037c47271d473459d9fec9"

      define_method(:install) do
        bin.install "relio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soyagvs/relio/releases/download/v1.3.0/relio_1.3.0_darwin_arm64.tar.gz"
      sha256 "e52b4caa0dc011c0b13178ce5f7d651bc410a689167711e01b894fd6033b3748"

      define_method(:install) do
        bin.install "relio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soyagvs/relio/releases/download/v1.3.0/relio_1.3.0_linux_amd64.tar.gz"
      sha256 "784a1cdea4bb4491ce0f049983dd3c4c2681e14da994126165f53f5c6729e375"
      define_method(:install) do
        bin.install "relio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soyagvs/relio/releases/download/v1.3.0/relio_1.3.0_linux_arm64.tar.gz"
      sha256 "23c4f78021f3281912a52ab2997cfe74256b0f581a41ae0e8c6526bd003bef71"
      define_method(:install) do
        bin.install "relio"
      end
    end
  end

  test do
    assert_match "Relio", shell_output("#{bin}/relio version")
  end
end
