# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relio < Formula
  desc "turn commits into releases"
  homepage "https://github.com/soyagvs/relio"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soyagvs/relio/releases/download/v1.1.1/relio_1.1.1_darwin_amd64.tar.gz"
      sha256 "a237b27394ec64542c7c8f7386a803eb157bbc677c654686fb40b30e0d8fbf27"

      define_method(:install) do
        bin.install "relio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soyagvs/relio/releases/download/v1.1.1/relio_1.1.1_darwin_arm64.tar.gz"
      sha256 "ee3b546852b0b6d17b385cd280f62ece0a3647b9cc9bf659990a7b78c39c6b5d"

      define_method(:install) do
        bin.install "relio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soyagvs/relio/releases/download/v1.1.1/relio_1.1.1_linux_amd64.tar.gz"
      sha256 "72b7deabbbf61b11885fa64842eaca0e37b9fea83da0a93a06e6e86401d4d746"
      define_method(:install) do
        bin.install "relio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soyagvs/relio/releases/download/v1.1.1/relio_1.1.1_linux_arm64.tar.gz"
      sha256 "25c72f19c98e4e93a80257b51660a3b6be81fd7c791e866216393087f44f2d41"
      define_method(:install) do
        bin.install "relio"
      end
    end
  end

  test do
    assert_match "Relio", shell_output("#{bin}/relio version")
  end
end
